server:
  # 配置服务提供者service-provider-1运行实例instance-1的端口
  port: 8765
eureka:
  client:
    service-url:
      defaultZone:
        #向注册中心节点1注册服务
        http://registry-server-1:8761/eureka
logging:
  file: "logs/service-provider-1-instance1.log"
management:
  security:
    enabled: false
spring:
  boot:
    admin:
      client:
        url:
          http://registry-server-1:5001
foo: foo version 1 git
